version: '3'
services:
  syslog-ng:
    image: balabit/syslog-ng
    volumes:
      - /tmp/syslog-ng:/tmp/syslog-ng
      - ./etc/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "localhost: 127.0.0.1"
  kafka:
    image: confluentinc/cp-kafka:4.1.1
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29093,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "localhost: 127.0.0.1"
  schema-registry:
    image: confluentinc/cp-schema-registry:4.1.1
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:32181'
  northstar-parse:
    depends_on:
      - syslog-ng
      - kafka
      - schema-registry
    environment:
      BOOTSTRAP_SERVERS: kafka:29093
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
    build:
      context: parse
    volumes:
      - /tmp/syslog-ng:/tmp/syslog-ng
  northstar-http:
    ports:
      - 8080:8080
    depends_on:
      - syslog-ng
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:29093
    build:
      context: http